services:
  portland-art-supply:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html
      - ./includes:/var/www/html/includes
      - ./vendor:/var/www/html/vendor
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  pas_net:
    name: pas_net
    driver: bridge
    external: true
